<?php

########################################################################
# Extension Manager/Repository config file for ext: "giftcertificates"
#
# Auto generated by Extension Builder 2011-10-29
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Gift certificates',
	'description' => 'A flexible system which helps you to create and display beautiful and flexible gift certificates on your website and gives your visitors the possibility to add a personal touch by modifying defined parts of the gift certificate.',
	'category' => 'plugin',
	'author' => 'Thomas Juhnke',
	'author_email' => 'tommy@van-tomas.de',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'cms' => '',
			'extbase' => '',
			'fluid' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>